# Eye tracking analyses 2025 Gap Overlap

In [421]:
import pandas as pd
from pathlib import Path
import numpy as np
import time
import os
import statsmodels
import seaborn as sns
import matplotlib.pyplot as plt
import glob
from scipy import stats
import pingouin as pg
import scikit_posthocs as sp
import statsmodels.api as sm
from scipy.stats import boxcox
from statannotations.Annotator import Annotator
from scipy.stats import pearsonr
import docx
from docx.enum.section import WD_ORIENT
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [422]:
# Papermill parameters
date = "2025_11_05"

In [423]:
# Function to convert df to docx table format

def df_to_table(doc, df):
    # Add a table to the end and create a reference variable
    t = doc.add_table(df.shape[0]+1, df.shape[1])

    # Make sure df is rounded 
    df = df.round(2)

    # Make sure table is auto fit
    for cell in t._cells:
        cell.width = docx.shared.Inches(1.0)
    
    # Set the style of the table
    table_style = doc.styles['Table Grid']

    # Add the header rows.
    for j in range(df.shape[-1]):
        t.cell(0,j).text = df.columns[j]

    # Add the rest of the data frame
    for i in range(df.shape[0]):
        for j in range(df.shape[-1]):
            t.cell(i+1,j).text = str(df.values[i,j])
    
    return doc

In [424]:
# Date 
date

'2025_11_05'

#### Create a word document with results

In [425]:
# Create a document

doc = docx.Document()

# Title page
section = doc.sections[0]
#section.start_type = WD_SECTION.ODD_PAGE
#section.orientation = WD_ORIENT.LANDSCAPE
#section.page_width, section.page_height = section.page_height, section.page_width

title = doc.add_paragraph()
title_run = title.add_run("Gap Overlap Eye Tracking Analysis Results")
title_run.bold = True
title_run.font.size = Pt(28)
title_run.font.name = 'Arial'
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_paragraph("")
doc.add_paragraph(f"Date: {date}").alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.add_paragraph("Author: Gabriel Blanco").alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.add_page_break()

# Add new doc section with landscape orientation
section = doc.add_section()
section.start_type = WD_SECTION.ODD_PAGE
new_width, new_height = section.page_height, section.page_width
section.orientation = WD_ORIENT.LANDSCAPE
section.page_width = new_width


doc.add_heading(f"Gap Analysis results", 0)

# Add heading

doc.add_heading('Participants', level=1)
doc.add_paragraph("This section describes the participants included in the analysis after initial filtering and demographic merging.")

## Data loading

In [426]:
# Load all the files
go_files = glob.glob(f"C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files/*.txt")
p1= f"Total files including tests: " + str(len(go_files))
go_files

['C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\002_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0042P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0043F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\004_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0050M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0050P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0062P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0064M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0064S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0068F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0068M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0068S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0068S3_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\006_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0083F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0083M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0083P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0086F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0086M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0086S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\008_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0093O1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\009_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0104P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0105F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0105P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\010_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0111F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0111M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0119M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0128P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0129M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\012_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0131M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0131P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0131S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0134F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0134M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0134S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\013_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0146P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0147F2_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0147M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0147P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\014_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0150M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0152M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0154P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0157M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0159M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\015_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0162M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0162P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0162S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0171F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0171M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0171P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0175F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0175M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0175P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0179M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0179P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\017_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0181F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0181M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0181P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0183M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0183P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0183S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0186F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0186M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\018_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0196M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0196P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0196S2_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0200F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0200M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0200P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0200S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\020_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0212F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0212P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0212S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0216M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0216P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0218M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0218P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0223M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0223P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0223S2_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0225F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0225M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0225P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227S2_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227S3_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0227S4_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0231M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0231P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0231S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0231S2_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0239M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0239P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\023_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0248F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0248M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0248P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0248S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\024_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0259F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0259M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0259P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0259S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0265M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0265P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\026_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0275F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0275P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\027_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0281M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0281P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0286F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0286M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0286S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\028_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0296F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0296M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0296P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0296S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\029_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0301M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0309F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0309M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0309P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\030_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0315M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0315P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\031_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0320M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0320P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0326M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0326P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0326S1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0329M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\032_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0331M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0333F1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0333M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\033_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0344M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\0344P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\038_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\052_Z_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\1006M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\1006P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\1009M1_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\1009P_GO.txt',
 'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\\1009S1_GO.txt',

In [427]:
# Load all the files into a single dataframe
df = []

# Create a dictionary to store empty subjects
subjects_removed = {}
for file in go_files:
    # Load experimental participants
    print(file)
    temp_df=pd.read_table(file)
    print("Completed")
    temp_df = pd.read_csv(file, delimiter = "\t")
    id= file.split("\\")[-1].split(".")[0].replace("_GO", "")
    print(id)
    if len(temp_df) == 0:
        print(f"Empty file: {id}")       
    # Save the empty subjects id to dictionary and include label "empty"
        subjects_removed[id] = "empty file"
        continue
    temp_df["subject"] = id
    # Load pilot participants
    if "Z" in id:
        alphanum = id.split("_")[0]
        family_id = "Z"
        temp_df["subject"] = alphanum + family_id
    df.append(temp_df)
go_df = pd.concat(df, axis=0)
go_df

C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\002_Z_GO.txt
Completed
002_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0042P_GO.txt
Completed
0042P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0043F1_GO.txt
Completed
0043F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\004_Z_GO.txt
Completed
004_Z
Empty file: 004_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0050M1_GO.txt
Completed
0050M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0050P_GO.txt
Completed
0050P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0062P_GO.txt
Completed
0062P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0064M1_GO.txt
Completed
0064M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0064S1_GO.txt
Completed
0064S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0068F1_GO.txt
Completed
0068F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0068M1_GO.txt
Completed
0068M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0068S1_GO.txt
Completed
0068S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0068S3_GO.txt
Completed
0068S3
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\006_Z_GO.txt
Completed
006_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0083F1_GO.txt
Completed
0083F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0083M1_GO.txt
Completed
0083M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0083P_GO.txt
Completed
0083P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0086F1_GO.txt
Completed
0086F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0086M1_GO.txt
Completed
0086M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0086S1_GO.txt
Completed
0086S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\008_Z_GO.txt
Completed
008_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0093O1_GO.txt
Completed
0093O1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\009_Z_GO.txt
Completed
009_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0104P_GO.txt
Completed
0104P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0105F1_GO.txt
Completed
0105F1
Empty file: 0105F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0105P_GO.txt
Completed
0105P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\010_Z_GO.txt
Completed
010_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0111F1_GO.txt
Completed
0111F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0111M1_GO.txt
Completed
0111M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0119M1_GO.txt
Completed
0119M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0128P_GO.txt
Completed
0128P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0129M1_GO.txt
Completed
0129M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\012_Z_GO.txt
Completed
012_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0131M1_GO.txt
Completed
0131M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0131P_GO.txt
Completed
0131P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0131S1_GO.txt
Completed
0131S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0134F1_GO.txt
Completed
0134F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0134M1_GO.txt
Completed
0134M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0134S1_GO.txt
Completed
0134S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\013_Z_GO.txt
Completed
013_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0146P_GO.txt
Completed
0146P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0147F2_GO.txt
Completed
0147F2
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0147M1_GO.txt
Completed
0147M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0147P_GO.txt
Completed
0147P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\014_Z_GO.txt
Completed
014_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0150M1_GO.txt
Completed
0150M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0152M1_GO.txt
Completed
0152M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0154P_GO.txt
Completed
0154P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0157M1_GO.txt
Completed
0157M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0159M1_GO.txt
Completed
0159M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\015_Z_GO.txt
Completed
015_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0162M1_GO.txt
Completed
0162M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0162P_GO.txt
Completed
0162P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0162S1_GO.txt
Completed
0162S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0171F1_GO.txt
Completed
0171F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0171M1_GO.txt
Completed
0171M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0171P_GO.txt
Completed
0171P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0175F1_GO.txt
Completed
0175F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0175M1_GO.txt
Completed
0175M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0175P_GO.txt
Completed
0175P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0179M1_GO.txt
Completed
0179M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0179P_GO.txt
Completed
0179P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\017_Z_GO.txt
Completed
017_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0181F1_GO.txt
Completed
0181F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0181M1_GO.txt
Completed
0181M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0181P_GO.txt
Completed
0181P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0183M1_GO.txt
Completed
0183M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0183P_GO.txt
Completed
0183P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0183S1_GO.txt
Completed
0183S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0186F1_GO.txt
Completed
0186F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0186M1_GO.txt
Completed
0186M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\018_Z_GO.txt
Completed
018_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0196M1_GO.txt
Completed
0196M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0196P_GO.txt
Completed
0196P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0196S2_GO.txt
Completed
0196S2
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0200F1_GO.txt
Completed
0200F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0200M1_GO.txt
Completed
0200M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0200P_GO.txt
Completed
0200P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0200S1_GO.txt
Completed
0200S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\020_Z_GO.txt
Completed
020_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0212F1_GO.txt
Completed
0212F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0212P_GO.txt
Completed
0212P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0212S1_GO.txt
Completed
0212S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0216M1_GO.txt
Completed
0216M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0216P_GO.txt
Completed
0216P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0218M1_GO.txt
Completed
0218M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0218P_GO.txt
Completed
0218P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0223M1_GO.txt
Completed
0223M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0223P_GO.txt
Completed
0223P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0223S2_GO.txt
Completed
0223S2
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0225F1_GO.txt
Completed
0225F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0225M1_GO.txt
Completed
0225M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0225P_GO.txt
Completed
0225P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227F1_GO.txt
Completed
0227F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227M1_GO.txt
Completed
0227M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227P_GO.txt
Completed
0227P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227S1_GO.txt
Completed
0227S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227S2_GO.txt
Completed
0227S2
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227S3_GO.txt
Completed
0227S3
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0227S4_GO.txt
Completed
0227S4
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0231M1_GO.txt
Completed
0231M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0231P_GO.txt
Completed
0231P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0231S1_GO.txt
Completed
0231S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0231S2_GO.txt
Completed
0231S2
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0239M1_GO.txt
Completed
0239M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0239P_GO.txt
Completed
0239P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\023_Z_GO.txt
Completed
023_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0248F1_GO.txt
Completed
0248F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0248M1_GO.txt
Completed
0248M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0248P_GO.txt
Completed
0248P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0248S1_GO.txt
Completed
0248S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\024_Z_GO.txt
Completed
024_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0259F1_GO.txt
Completed
0259F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0259M1_GO.txt
Completed
0259M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0259P_GO.txt
Completed
0259P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0259S1_GO.txt
Completed
0259S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0265M1_GO.txt
Completed
0265M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0265P_GO.txt
Completed
0265P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\026_Z_GO.txt
Completed
026_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0275F1_GO.txt
Completed
0275F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0275P_GO.txt
Completed
0275P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\027_Z_GO.txt
Completed
027_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0281M1_GO.txt
Completed
0281M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0281P_GO.txt
Completed
0281P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0286F1_GO.txt
Completed
0286F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0286M1_GO.txt
Completed
0286M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0286S1_GO.txt
Completed
0286S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\028_Z_GO.txt
Completed
028_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0296F1_GO.txt
Completed
0296F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0296M1_GO.txt
Completed
0296M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0296P_GO.txt
Completed
0296P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0296S1_GO.txt
Completed
0296S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\029_Z_GO.txt
Completed
029_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0301M1_GO.txt
Completed
0301M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0309F1_GO.txt
Completed
0309F1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0309M1_GO.txt
Completed
0309M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0309P_GO.txt
Completed
0309P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\030_Z_GO.txt
Completed
030_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0315M1_GO.txt
Completed
0315M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0315P_GO.txt
Completed
0315P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\031_Z_GO.txt
Completed
031_Z
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0320M1_GO.txt
Completed
0320M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0320P_GO.txt
Completed
0320P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0326M1_GO.txt
Completed
0326M1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0326P_GO.txt
Completed
0326P
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0326S1_GO.txt
Completed
0326S1
C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/GO_files/all_files\0329M1_GO.txt
Completed
0329M1

,Session_Name_,Trial_Index_,Trial_Recycled_,task,condition,detail,GO_JITTER,GO_SAC_RT,GO_VALID,subject
0,s02,1,False,GO,Baseline,Right,42,230.31,True,002Z
1,s02,2,False,GO,Gap,Right,64,255.00,True,002Z
2,s02,3,False,GO,Overlap,Left,72,323.78,True,002Z
3,s02,4,False,GO,Gap,Right,29,197.00,True,002Z
4,s02,5,False,GO,Baseline,Left,83,372.62,True,002Z
...,...,...,...,...,...,...,...,...,...,...
32,052_go_1,33,False,GO,Overlap,Left,83,366.80,True,sub-052Z
33,052_go_1,34,False,GO,Gap,Right,30,216.00,True,sub-052Z
34,052_go_1,35,False,GO,Overlap,Left,52,312.28,True,sub-052Z
35,052_go_1,36,False,GO,Baseline,Left,62,311.04,True,sub-052Z
36,052_go_1,37,False,GO,Baseline,Left,26,251.79,True,sub-052Z

In [428]:
# Total number of subjects after firts filtering
doc.add_heading('Total number of subjects after first filtering', level=2)

# Add the unique subjects to the document

# Add total number of subject files
doc.add_paragraph(f"Total number of subject files: {len(go_files)}", style='List Bullet')
# Print percetage of empty subjects
empty_subjects_count = len(subjects_removed)
total_subjects = len(go_df.subject.unique())
doc.add_paragraph(f"Total number of empty subjects: {empty_subjects_count}", style='List Bullet')
doc.add_paragraph(f"Percentage of empty subjects: {empty_subjects_count/total_subjects*100:.2f}%", style='List Bullet')

# Print on this notebook as well
print(f"Total number of subject files: {len(go_files)}")
print(f"Percentage of empty subjects: {empty_subjects_count} ({empty_subjects_count/total_subjects*100:.2f}%)")

# Print the unique subjects
print(f"Total number of subjects after first filtering: {len(go_df.subject.unique())}")

# Add the unique subjects to the document
doc.add_paragraph(f"Total number of subjects after first filtering: {len(go_df.subject.unique())}", style='List Bullet')

Total number of subject files: 285
Percentage of empty subjects: 12 (4.40%)
Total number of subjects after first filtering: 273

In [429]:
# Print the unique subjects
go_df.subject.unique()

array(['002Z', '0042P', '0043F1', '0050M1', '0050P', '0062P', '0064M1',
       '0064S1', '0068F1', '0068M1', '0068S1', '0068S3', '006Z', '0083F1',
       '0083M1', '0083P', '0086F1', '0086M1', '0086S1', '008Z', '0093O1',
       '009Z', '0104P', '0105P', '010Z', '0111F1', '0111M1', '0119M1',
       '0128P', '0129M1', '012Z', '0131M1', '0131P', '0131S1', '0134F1',
       '0134M1', '0134S1', '013Z', '0146P', '0147F2', '0147M1', '0147P',
       '014Z', '0150M1', '0152M1', '0154P', '0157M1', '0159M1', '015Z',
       '0162M1', '0162P', '0162S1', '0171F1', '0171M1', '0171P', '0175F1',
       '0175M1', '0175P', '0179M1', '0179P', '017Z', '0181F1', '0181M1',
       '0181P', '0183M1', '0183P', '0183S1', '0186F1', '0186M1', '018Z',
       '0196M1', '0196P', '0196S2', '0200F1', '0200M1', '0200P', '0200S1',
       '020Z', '0212F1', '0212P', '0212S1', '0216M1', '0216P', '0218M1',
       '0218P', '0223M1', '0223P', '0223S2', '0225F1', '0225M1', '0225P',
       '0227F1', '0227M1', '0227P', '0227S1', '0227S2', '0227S3',
       '0227S4', '0231M1', '0231P', '0231S1', '0231S2', '0239M1', '0239P',
       '023Z', '0248F1', '0248M1', '0248P', '0248S1', '024Z', '0259F1',
       '0259M1', '0259P', '0259S1', '0265M1', '0265P', '026Z', '0275F1',
       '0275P', '027Z', '0281M1', '0281P', '0286F1', '0286M1', '0286S1',
       '028Z', '0296F1', '0296M1', '0296P', '0296S1', '029Z', '0301M1',
       '0309F1', '0309M1', '0309P', '030Z', '0315M1', '0315P', '031Z',
       '0320M1', '0320P', '0326M1', '0326P', '0326S1', '0329M1', '032Z',
       '0331M1', '0333F1', '0333M1', '033Z', '0344M1', '0344P', '038Z',
       '052Z', '1006M1', '1009M1', '1009P', '1009S1', '1024M1', '1024P',
       '1026M1', '1026P', '1028P', '1028S1', '1028S2', '1033M1', '1033P',
       '1033S1', '1037F1', '1037P', '1040M1', '1040P', '1042F1', '1042M1',
       '1042P', '1045P', '1045S1', '1052F1', '1052M1', '1052S1', '1057M1',
       '1057P', '1061F1', '1061M1', '1061S3', '1067M1', '1067P', '1067S1',
       '1073M1', '1073P', '1078F1', '1078P', '1080F1', '1080M1', '1080P',
       '1083F1', '1083P', '1083S1', '1089S1', '1093P', '1093S1', '1093S2',
       '1101P', '1102P', '1102S1', '1102S2', '1106F1', '1106M1', '1106P',
       '1109F1', '1109M1', '1109P', '1112M1', '1112P', '1114P', '1118F1',
       '1118M1', '1118P', '1121F1', '1121M1', '1121P', '1121S1', '1125P',
       '1134M1', '1134S1', '1140S1', '1143F1', '1143P', '1147F1', '1147P',
       '1147S1', '1152S1', '1156F1', '1159P', '1159S1', '1159S2',
       '1162M1', '1162S1', '1166F1', '1166P', '1169F1', '1169M1', '1169P',
       '1182F1', '1182M1', '1182P', '1187P', '1192F1', '1192M1', '1192S1',
       '1195P', '1195S1', '1195S2', '1200P', '1203F1', '1203P', '1203S2',
       '1203S3', '1209M1', '1209P', '1212M1', '1221P', '1222P', '1222S1',
       '1222S2', '1226M1', '1226M2', '1226P', '1256F1', '1256P', '1256S1',
       '1256S2', 'sub-052Z'], dtype=object)

#### Keep only relevant columns

In [430]:
## keep only the relevant columns
go_df = go_df[["subject","Trial_Index_","condition", "detail", "GO_SAC_RT", "GO_VALID"]]
go_df

     subject  Trial_Index_ condition detail  GO_SAC_RT  GO_VALID
0       002Z             1  Baseline  Right     230.31      True
1       002Z             2       Gap  Right     255.00      True
2       002Z             3   Overlap   Left     323.78      True
3       002Z             4       Gap  Right     197.00      True
4       002Z             5  Baseline   Left     372.62      True
..       ...           ...       ...    ...        ...       ...
32  sub-052Z            33   Overlap   Left     366.80      True
33  sub-052Z            34       Gap  Right     216.00      True
34  sub-052Z            35   Overlap   Left     312.28      True
35  sub-052Z            36  Baseline   Left     311.04      True
36  sub-052Z            37  Baseline   Left     251.79      True

[9857 rows x 6 columns]

#### Load demographic data

In [431]:
# Load demographic data
demo_df = pd.read_csv(f'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/demographics_redcap/participants.tsv', 
                      sep="\t", encoding='utf-8', low_memory=False)

asd_df=pd.read_csv(f'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/outputs/diagnosis/asd_diagnosis.csv',
                   encoding='utf-8', low_memory=False)

In [432]:
# Drop columns asd, ndd registry_confirmed_asd
demo_df= demo_df.drop(columns=['asd', 'ndd', 'registry_confirmed_asd'])
# Merge with asd diagnosis
demo_df = demo_df.merge(asd_df, left_on='bids_id', right_on='subject', how='left')

In [433]:
demo_df

,participant_id,bids_id,site,sex,eeg_age,group,age_group,registry_confirmed_language_disorder,asd_healthform,adhd,...,q1k_ID_x,q1k_ID_y,asd_psq,name_matching_confidence,enrol_asd,ndd,medical_records_asd,asd_match,asd,subject
0,sub-0042P,0042P,MNI,female,30.97,proband,adult,NaN,NaN,0.0,...,Q1K_MHC_20042_P,Q1K_MHC_20042_P,NaN,NaN,0.0,1.0,NaN,NaN,0.0,0042P
1,sub-0043F1,0043F1,HSJ,male,58.13,father,adult,NaN,0,1.0,...,Q1K_HSJ_10043_F1,Q1K_HSJ_10043_F1,0.0,high_confidence,0.0,0.0,0.0,match,0.0,0043F1
2,sub-0043P,0043P,HSJ,male,16.91,proband,child,NaN,0,1.0,...,Q1K_HSJ_10043_P,Q1K_HSJ_10043_P,NaN,NaN,0.0,1.0,0.0,NaN,0.0,0043P
3,sub-0050M1,0050M1,HSJ,female,37.10,mother,adult,NaN,NaN,NaN,...,Q1K_HSJ_10050_M1,Q1K_HSJ_10050_M1,0.0,high_confidence,NaN,0.0,NaN,NaN,0.0,0050M1
4,sub-0050P,0050P,HSJ,female,8.07,proband,child,2.0,0,1.0,...,Q1K_HSJ_10050_P,Q1K_HSJ_10050_P,NaN,NaN,0.0,1.0,0.0,NaN,0.0,0050P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,sub-1256S1,1256S1,HSJ,male,17.33,sibling,child,NaN,0,NaN,...,Q1K_HSJ_1525-1256_S1,Q1K_HSJ_1525-1256_S1,0.0,high_confidence,1.0,1.0,0.0,mismatch,1.0,1256S1
294,sub-1256S2,1256S2,HSJ,female,18.32,sibling,adult,NaN,1,NaN,...,Q1K_HSJ_1525-1256_S2,Q1K_HSJ_1525-1256_S2,1.0,exact,1.0,1.0,1.0,NaN,1.0,1256S2
295,sub-1261F1,1261F1,HSJ,male,40.24,father,adult,NaN,NaN,NaN,...,Q1K_HSJ_1525-1261_F1,Q1K_HSJ_1525-1261_F1,0.0,high_confidence,NaN,0.0,NaN,NaN,0.0,1261F1
296,sub-1261P,1261P,HSJ,male,7.71,proband,child,2.0,1,0.0,...,Q1K_HSJ_1525-1261_P,Q1K_HSJ_1525-1261_P,NaN,NaN,1.0,1.0,1.0,NaN,1.0,1261P
297,sub-1285P,1285P,HSJ,female,6.47,proband,child,NaN,0,NaN,...,Q1K_HSJ_1525-1285_P,Q1K_HSJ_1525-1285_P,NaN,NaN,1.0,1.0,0.0,NaN,1.0,1285P

In [434]:
demo_df["subject"]=demo_df["bids_id"]

#### Load the Pilot data

In [439]:
pilot_demodf = pd.read_csv(f'C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/source/demographics_redcap/pilot_participants.csv', 
                        encoding='utf-8', low_memory=False)

In [440]:
pilot_demodf

       sex  eeg_age site     q1k_ID  ndd  asd  group age_group subject  fam_id
0   Female    45.88  MNI  Q1K_002_Z    0    0    NaN     adult    002Z     NaN
1   Female    11.13  MNI  Q1K_004_Z    0    0    NaN     child    004Z     3.0
2     Male    33.64  MNI  Q1K_006_Z    0    0    NaN     adult    006Z     NaN
3   Female    23.50  MNI  Q1K_007_Z    0    0    NaN     adult    007Z     NaN
4     Male    40.47  MNI  Q1K_008_Z    0    0    NaN     adult    008Z     4.0
5   Female    23.77  MNI  Q1K_009_Z    0    0    NaN     adult    009Z     NaN
6   Female    28.98  MNI  Q1K_010_Z    0    0    NaN     adult    010Z     NaN
7   Female    32.10  MNI  Q1K_011_Z    0    0    NaN     adult    011Z     NaN
8   Female    23.66  MNI  Q1K_012_Z    0    0    NaN     adult    012Z     NaN
9   Female    22.43  MNI  Q1K_013_Z    0    0    NaN     adult    013Z     NaN
10  Female    24.42  MNI  Q1K_014_Z    0    0    NaN     adult    014Z     NaN
11  Female    23.96  MNI  Q1K_015_Z    0    0    NaN     adult    015Z     NaN
12    Male    11.05  MNI  Q1K_017_Z    0    0    NaN     child    017Z     4.0
13  Female    23.44  MNI  Q1K_018_Z    0    0    NaN     adult    018Z     NaN
14  Female    25.77  MNI  Q1K_019_Z    0    0    NaN     adult    019Z     NaN
15  Female    44.97  MNI  Q1K_020_Z    0    0    NaN     adult    020Z     3.0
16  Female    24.75  MNI  Q1K_022_Z    0    0    NaN     adult    022Z     NaN
17  Female    23.89  MNI  Q1K_023_Z    0    0    NaN     adult    023Z     NaN
18  Female    23.48  MNI  Q1K_024_Z    0    0    NaN     adult    024Z     NaN
19  Female    25.86  MNI  Q1K_025_Z    0    0    NaN     adult    025Z     NaN
20  Female    61.33  MNI  Q1K_026_Z    0    0    NaN     adult    026Z     NaN
21  Female    39.95  MNI  Q1K_027_Z    0    0    NaN     adult    027Z     NaN
22  Female    24.09  MNI  Q1K_028_Z    0    0    NaN     adult    028Z     NaN
23  Female    36.22  MNI  Q1K_029_Z    0    0    NaN     adult    029Z     NaN
24  Female    30.98  MNI  Q1K_030_Z    0    0    NaN     adult    030Z     NaN
25    Male    28.27  MNI  Q1K_031_Z    0    0    NaN     adult    031Z     NaN
26  Female    18.20  MNI  Q1K_032_Z    0    0    NaN     adult    032Z     NaN
27    Male     9.88  MNI  Q1K_033_Z    0    0    NaN     child    033Z     NaN
28    Male    10.63  MNI  Q1K_038_Z    0    0    NaN     child    038Z     NaN
29  Female    16.53  MNI  Q1K_052_Z    0    0    NaN     child    052Z     NaN

In [441]:
# Change sex column to lowercase
pilot_demodf.loc[:, "sex"] = pilot_demodf["sex"].str.lower()

In [442]:
# drop trailing spaces
demo_df.loc[:,'subject'] = demo_df['subject'].str.strip()

#### Merge pilot and experimental data

In [443]:
demo_df = pd.concat([demo_df, pilot_demodf], axis=0)

In [444]:
# Remove participants more than 80% missing data
missing_data_threshold = 0.8
demo_df = demo_df[demo_df["subject"].notna()]
missing_data = demo_df.isnull().mean(axis=1)    
demo_df = demo_df[missing_data < missing_data_threshold]

# Add section about demographics filtering
doc.add_heading('Demographics Filtering', level=2)

# Add subheading for demographics filtering
doc.add_paragraph("This section describes the participants included in the analysis after demographic filtering.")

# Add number of subjects with missing data to the document
doc.add_paragraph(f"Total number of subjects with missing data: {len(demo_df[missing_data > missing_data_threshold])}", style='List Bullet')

In [446]:
# Keep important columns
demo_df = demo_df[["subject", "eeg_age",  "site", "sex","asd", "ndd", "q1k_ID", "group", 'age_group',"fam_id"]]

# Change NDD from 0, 1 to "ndd" and "control"
demo_df.loc[:, "ndd"] = demo_df["ndd"].replace({0: "control", 1: "ndd"})

# Change site to lowercase
demo_df.loc[:, "site"] = demo_df["site"].str.lower()

C:\Users\gabot\AppData\Local\Temp\ipykernel_9628\328419604.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['ndd' 'control' 'ndd' 'control' 'ndd' 'control' 'control' 'control' 'ndd'
 'ndd' 'control' 'control' 'ndd' 'control' 'ndd' 'ndd' 'ndd' 'control'
 'control' 'ndd' 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'ndd'
 'ndd' 'control' 'control' 'control' 'ndd' 'control' 'control' 'ndd'
 'control' 'control' 'control' 'control' 'ndd' 'control' 'control' 'ndd'
 'ndd' 'ndd' 'control' 'ndd' 'control' 'ndd' 'control' 'ndd' 'control'
 'ndd' 'control' 'ndd' 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'ndd'
 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'ndd' 'control' 'control' 'control'
 'ndd' 'control' 'ndd' 'control' 'ndd' 'control' 'ndd' 'control' 'control'
 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'control' 'control' 'ndd' 'control'
 'control' 'control' 'ndd' 'control' 'control' 'ndd' 'control' 'ndd' 'ndd'
 'control' 'ndd' 'control' 'ndd' 'ndd' 'control' 'control' 'ndd' 'ndd'
 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'ndd' 'ndd' 'control' 'ndd' 'control'
 'ndd' 'ndd' 'control' 'ndd' 'ndd' 'ndd' 'control' 'control' 'control'
 'ndd' 'ndd' 'ndd' 'control' 'ndd' 'control' 'control' 'control' 'ndd'
 'control' 'ndd' 'ndd' 'control' nan 'ndd' 'ndd' 'control' 'ndd' 'control'
 'control' 'ndd' 'ndd' 'control' 'control' 'control' 'ndd' 'control'
 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'ndd' 'ndd' 'ndd'
 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'ndd' 'ndd' 'control' 'ndd'
 'ndd' 'ndd' 'control' 'control' 'ndd' 'ndd' 'ndd' 'control' 'control'
 'control' 'ndd' 'control' 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd'
 'ndd' 'ndd' 'control' 'control' 'ndd' 'control' 'ndd' 'ndd' 'control'
 'ndd' 'control' 'ndd' 'control' 'control' 'ndd' 'control' 'ndd' 'ndd'
 'control' 'ndd' 'ndd' 'control' 'control' 'ndd' 'control' 'ndd' 'control'
 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'control' 'ndd'
 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'control' 'control' 'ndd' 'ndd'
 'ndd' 'ndd' 'control' 'ndd' 'ndd' 'control' 'ndd' 'control' 'control'
 'ndd' 'control' 'control' 'ndd' 'ndd' 'ndd' 'control' 'ndd' 'ndd'
 'control' 'control' 'ndd' 'control' 'ndd' 'ndd' 'control' 'control' 'ndd'
 'control' 'ndd' 'control' 'control' 'ndd' 'ndd' 'ndd' 'control' 'ndd'
 'control' 'ndd' 'control' 'ndd' 'control' 'ndd' 'control' 'ndd' 'ndd'
 'control' 'ndd' 'control' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'ndd' 'control'
 'ndd' 'ndd' 'control' 'control' 'control' 'control' 'control' 'control'
 'control' 'control' 'control' 'control' 'control' 'control' 'control'
 'control' 'control' 'control' 'control' 'control' 'control' 'control'
 'control' 'control' 'control' 'control' 'control' 'control' 'control'
 'control' 'control' 'control']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  demo_df.loc[:, "ndd"] = demo_df["ndd"].replace({0: "control", 1: "ndd"})

In [458]:
# Create family ID for those that are missing family id already
mask = demo_df["fam_id"].isna()
demo_df.loc[mask, "fam_id"] = demo_df.loc[mask, "subject"].str.extract(r"(\d+)", expand=False)

# Make sure it has four digits and its a integer
demo_df["fam_id"] = demo_df["fam_id"].astype(float).astype(int).astype(str).str.zfill(4)

C:\Users\gabot\AppData\Local\Temp\ipykernel_9628\2687938862.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demo_df["fam_id"] = demo_df["fam_id"].astype(float).astype(int).astype(str).str.zfill(4)

In [460]:
demo_df

,subject,eeg_age,site,sex,asd,ndd,q1k_ID,group,age_group,fam_id
0,0042P,30.97,mni,female,0.0,ndd,NaN,proband,adult,0042
1,0043F1,58.13,hsj,male,0.0,control,NaN,father,adult,0043
2,0043P,16.91,hsj,male,0.0,ndd,NaN,proband,child,0043
3,0050M1,37.10,hsj,female,0.0,control,NaN,mother,adult,0050
4,0050P,8.07,hsj,female,0.0,ndd,NaN,proband,child,0050
...,...,...,...,...,...,...,...,...,...,...
25,031Z,28.27,mni,male,0.0,control,Q1K_031_Z,NaN,adult,0031
26,032Z,18.20,mni,female,0.0,control,Q1K_032_Z,NaN,adult,0032
27,033Z,9.88,mni,male,0.0,control,Q1K_033_Z,NaN,child,0033
28,038Z,10.63,mni,male,0.0,control,Q1K_038_Z,NaN,child,0038
29,052Z,16.53,mni,female,0.0,control,Q1K_052_Z,NaN,child,0052

### Sanity check to flag participants with no demographic data

In [461]:
for subject in go_df.subject.unique():
    if subject in demo_df.subject.unique():
        continue
    else: 
        print (f"Flag '{subject}'")
        # Add the subject to the dictionary with label "missing"
        subjects_removed[subject] = "missing demographic data"

Flag '0225P'
Flag '0259P'
Flag '0320P'
Flag '0326P'
Flag '0329M1'
Flag '0333M1'
Flag '0344M1'
Flag '0344P'
Flag 'sub-052Z'

In [462]:
# Keep only the subjects that are in the go_df 
demo_df = demo_df[demo_df.subject.isin(go_df.subject.unique())]

In [463]:
# Create new column for developmental groups (children, adolescents, adults)
demo_df['developmental_group'] = demo_df['eeg_age'].apply(
    lambda x: 'child' if x < 13 else ('adolescent' if 13 <= x < 18 else 'adult')
)
demo_df

C:\Users\gabot\AppData\Local\Temp\ipykernel_9628\1728720679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demo_df['developmental_group'] = demo_df['eeg_age'].apply(

,subject,eeg_age,site,sex,asd,ndd,q1k_ID,group,age_group,fam_id,developmental_group
0,0042P,30.97,mni,female,0.0,ndd,NaN,proband,adult,0042,adult
1,0043F1,58.13,hsj,male,0.0,control,NaN,father,adult,0043,adult
3,0050M1,37.10,hsj,female,0.0,control,NaN,mother,adult,0050,adult
4,0050P,8.07,hsj,female,0.0,ndd,NaN,proband,child,0050,child
6,0062P,40.61,hsj,female,0.0,control,NaN,proband,adult,0062,adult
...,...,...,...,...,...,...,...,...,...,...,...
25,031Z,28.27,mni,male,0.0,control,Q1K_031_Z,NaN,adult,0031,adult
26,032Z,18.20,mni,female,0.0,control,Q1K_032_Z,NaN,adult,0032,adult
27,033Z,9.88,mni,male,0.0,control,Q1K_033_Z,NaN,child,0033,child
28,038Z,10.63,mni,male,0.0,control,Q1K_038_Z,NaN,child,0038,child
29,052Z,16.53,mni,female,0.0,control,Q1K_052_Z,NaN,child,0052,adolescent

## Exploratory Analysis

In [464]:
# Total number of subjects
p2 = f"Total number of subjects after demographic filtering: {len(demo_df)}"
print (p2)
doc.add_paragraph(p2,style='List Bullet')

Total number of subjects after demographic filtering: 264

#### Age stats

In [465]:
# Age stats
p3 = f"Mean age: {demo_df.eeg_age.mean().round(2)}"
print (p3)

# Number of children

p4 = f"Number of children: {len(demo_df[demo_df.developmental_group == 'child'])}"
print (p4)

# number of adolescents
p5 = f"Number of adolescents: {len(demo_df[demo_df.developmental_group == 'adolescent'])}"
print (p5)

# Number of adults and children
p6 = f"Number of adults: {len(demo_df[demo_df.developmental_group == 'adult'])}"
print (p6)


# Add headings for age stats
doc.add_heading('Age statistics', level=2)
# Add age stats to the document
doc.add_paragraph(p3, style='List Bullet')
doc.add_paragraph(p4, style='List Bullet')
doc.add_paragraph(p5, style='List Bullet')
doc.add_paragraph(p6, style='List Bullet')

Mean age: 27.56
Number of children: 74
Number of adolescents: 41
Number of adults: 149

#### Sex

In [466]:
# Add heading for sex stats
doc.add_heading('Sex statistics', level=2)


# Number of female
p7 = f"Number of females: {len(demo_df[demo_df.sex == 'female'])}"
print (p7)

# Number of males
p8 = f"Number of male: {len(demo_df[demo_df.sex=='male'])}"
print (p8)

# Add sex stats to the document
doc.add_paragraph(p7, style='List Bullet')
doc.add_paragraph(p8, style='List Bullet')

Number of females: 143
Number of male: 120

#### Number of NDDs

In [467]:
# Add section for NDD statistics
doc.add_heading('NDD statistics', level=2)

# Number of NDD
p9 = f"Number of NDD: {len(demo_df[demo_df.ndd=='ndd'])}"
print (p9)

# Number of control
p10 = f"Number of control: {len(demo_df[demo_df.ndd=='control'])}"
print (p10)

# Add NDD stats to the document
doc.add_paragraph(p9, style='List Bullet')
doc.add_paragraph(p10, style='List Bullet')

Number of NDD: 136
Number of control: 127

#### Site Count

In [468]:
# Number of MNI
p11 = f"Number of mni: {len(demo_df[demo_df.site=='mni'])}"
print (p11)

# Number of HSJ
p12 = f"Number of hsj: {len(demo_df[demo_df.site=='hsj'])}"
print (p12)

Number of mni: 108
Number of hsj: 156

#### Famly dynamics

In [469]:
print(demo_df.group.value_counts())

# Add section for family groups
doc.add_heading('Family groups', level=2)
# Add the breakdown (group values counts) of family groups to the document
doc.add_paragraph(str(demo_df.group.value_counts()), style='List Bullet')

group
proband    73
mother     70
sibling    55
father     42
Name: count, dtype: int64

In [470]:
# Number of missing ASD diagnosis
p13 = f"Number of missing ASD diagnosis: {len(demo_df[demo_df.asd.isna()])}"
print (p13)

Number of missing ASD diagnosis: 2

### Demographics table by NDD

In [471]:
# Summarize data by diagnosis groups
summary_table = demo_df.groupby("ndd").agg(
    n=("ndd", "count"),
    male=("sex", lambda x: (x == "male").sum()),
    female=("sex", lambda x: (x == "female").sum()),
    mean_age=("eeg_age", "mean"),
    std_age=("eeg_age", "std"),
    hsj=("site", lambda x: (x == "hsj").sum()),
    mni=("site", lambda x: (x == "mni").sum()),
    adults=("developmental_group", lambda x: (x == "adult").sum()),
    children=("developmental_group", lambda x: (x == "child").sum()),
    adolescents=("developmental_group", lambda x: (x == "adolescent").sum()),
).reset_index()

# Add combined row for all participants
all_participants = {
    "ndd": "combined",
    "n": summary_table["n"].sum(),
    "male": summary_table["male"].sum(),
    "female": summary_table["female"].sum(),
    "mean_age": demo_df["eeg_age"].mean(),
    "std_age": demo_df["eeg_age"].std(),
    "hsj": summary_table["hsj"].sum(),
    "mni": summary_table["mni"].sum(),
    "children": summary_table["children"].sum(),
    "adolescents": summary_table["adolescents"].sum(),
        "adults": summary_table["adults"].sum(),

}

summary_table = pd.concat(
    [pd.DataFrame([all_participants]), summary_table], ignore_index=True
)

# Create combined and percentage columns
summary_table["sex (M:F)"] = summary_table["male"].astype(str) + ":" + summary_table["female"].astype(str)
summary_table["sex % (M:F)"] = (
    (summary_table["male"] / summary_table["n"] * 100).round(2).astype(str)
    + ":"
    + (summary_table["female"] / summary_table["n"] * 100).round(2).astype(str)
)

summary_table["site (HSJ:MNI)"] = summary_table["hsj"].astype(str) + ":" + summary_table["mni"].astype(str)
summary_table["site % (HSJ:MNI)"] = (
    (summary_table["hsj"] / summary_table["n"] * 100).round(2).astype(str)
    + ":"
    + (summary_table["mni"] / summary_table["n"] * 100).round(2).astype(str)
)

# Drop intermediate columns to keep the table clean
summary_table.drop(columns=["male", "female", "hsj", "mni"], inplace=True)

# Rename columns for better clarity
summary_table.rename(
    columns={
        "ndd": "NDD Group",
        "n": "Total Participants",
        "mean_age": "Mean Age",
        "std_age": "Age SD",
        "children": "Children",
        "adolescents": "Adolescents",
        "adults": "Adults",

    },
    inplace=True,
)

summary_table = summary_table.round(1)

In [472]:
summary_table

,NDD Group,Total Participants,Mean Age,Age SD,Children,Adolescents,Adults,sex (M:F),sex % (M:F),site (HSJ:MNI),site % (HSJ:MNI)
0,combined,263,27.6,16.6,74,41,148,119:143,45.25:54.37,156:107,59.32:40.68
1,control,127,34.8,15.9,20,8,99,45:82,35.43:64.57,64:63,50.39:49.61
2,ndd,136,20.7,14.2,54,33,49,74:61,54.41:44.85,92:44,67.65:32.35

In [473]:
## Add table to the document
doc.add_heading('Demographics breakdown by NDD', level=1)
doc.add_heading('Demographics table', level=3)
doc = df_to_table(doc, summary_table)

In [474]:
demo_df

,subject,eeg_age,site,sex,asd,ndd,q1k_ID,group,age_group,fam_id,developmental_group
0,0042P,30.97,mni,female,0.0,ndd,NaN,proband,adult,0042,adult
1,0043F1,58.13,hsj,male,0.0,control,NaN,father,adult,0043,adult
3,0050M1,37.10,hsj,female,0.0,control,NaN,mother,adult,0050,adult
4,0050P,8.07,hsj,female,0.0,ndd,NaN,proband,child,0050,child
6,0062P,40.61,hsj,female,0.0,control,NaN,proband,adult,0062,adult
...,...,...,...,...,...,...,...,...,...,...,...
25,031Z,28.27,mni,male,0.0,control,Q1K_031_Z,NaN,adult,0031,adult
26,032Z,18.20,mni,female,0.0,control,Q1K_032_Z,NaN,adult,0032,adult
27,033Z,9.88,mni,male,0.0,control,Q1K_033_Z,NaN,child,0033,child
28,038Z,10.63,mni,male,0.0,control,Q1K_038_Z,NaN,child,0038,child
29,052Z,16.53,mni,female,0.0,control,Q1K_052_Z,NaN,child,0052,adolescent

### Demographics table by ASD

In [475]:
# Summarize data by diagnosis groups
summary_table = demo_df.groupby("asd").agg(
    n=("asd", "count"),
    male=("sex", lambda x: (x == "male").sum()),
    female=("sex", lambda x: (x == "female").sum()),
    mean_age=("eeg_age", "mean"),
    std_age=("eeg_age", "std"),
    hsj=("site", lambda x: (x == "hsj").sum()),
    mni=("site", lambda x: (x == "mni").sum()),
    adults=("developmental_group", lambda x: (x == "adult").sum()),
    children=("developmental_group", lambda x: (x == "child").sum()),
    adolescents=("developmental_group", lambda x: (x == "adolescent").sum()),
).reset_index()

# Add combined row for all participants
all_participants = {
    "asd": "combined",
    "n": summary_table["n"].sum(),
    "male": summary_table["male"].sum(),
    "female": summary_table["female"].sum(),
    "mean_age": demo_df["eeg_age"].mean(),
    "std_age": demo_df["eeg_age"].std(),
    "hsj": summary_table["hsj"].sum(),
    "mni": summary_table["mni"].sum(),
    "children": summary_table["children"].sum(),
    "adolescents": summary_table["adolescents"].sum(),
        "adults": summary_table["adults"].sum(),

}

summary_table = pd.concat(
    [pd.DataFrame([all_participants]), summary_table], ignore_index=True
)

# Create combined and percentage columns
summary_table["sex (M:F)"] = summary_table["male"].astype(str) + ":" + summary_table["female"].astype(str)
summary_table["sex % (M:F)"] = (
    (summary_table["male"] / summary_table["n"] * 100).round(2).astype(str)
    + ":"
    + (summary_table["female"] / summary_table["n"] * 100).round(2).astype(str)
)

summary_table["site (HSJ:MNI)"] = summary_table["hsj"].astype(str) + ":" + summary_table["mni"].astype(str)
summary_table["site % (HSJ:MNI)"] = (
    (summary_table["hsj"] / summary_table["n"] * 100).round(2).astype(str)
    + ":"
    + (summary_table["mni"] / summary_table["n"] * 100).round(2).astype(str)
)

# Drop intermediate columns to keep the table clean
summary_table.drop(columns=["male", "female", "hsj", "mni"], inplace=True)

# Rename columns for better clarity
summary_table.rename(
    columns={
        "asd": "ASD Group",
        "n": "Total Participants",
        "mean_age": "Mean Age",
        "std_age": "Age SD",
        "children": "Children",
        "adolescents": "Adolescents",
                "adults": "Adults",

    },
    inplace=True,
)
summary_table = summary_table.round(1)

In [476]:
summary_table

,ASD Group,Total Participants,Mean Age,Age SD,Children,Adolescents,Adults,sex (M:F),sex % (M:F),site (HSJ:MNI),site % (HSJ:MNI)
0,combined,262,27.6,16.6,74,41,147,120:141,45.8:53.82,154:108,58.78:41.22
1,0.0,207,30.6,16.5,47,26,134,85:121,41.06:58.45,118:89,57.0:43.0
2,1.0,55,15.7,10.2,27,15,13,35:20,63.64:36.36,36:19,65.45:34.55

In [477]:
# Add table to the document
doc.add_heading('Demographics breakdown by ASD', level=1)
doc = df_to_table(doc, summary_table)

### Demographics by Affected status

In [478]:
# create a column for ASD vs affected-Non ASD vs non-affected based on asd and NDD 
demo_df['affected_group'] = demo_df.apply(
    lambda row: 'asd' if row['asd'] == 1 else ('affected' if row['ndd'] == 'ndd' else 'non-affected'),
    axis=1
)

C:\Users\gabot\AppData\Local\Temp\ipykernel_9628\3934803140.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demo_df['affected_group'] = demo_df.apply(

In [479]:
# Summarize data by diagnosis groups
summary_table = demo_df.groupby("affected_group").agg(
    n=("affected_group", "count"),
     male=("sex", lambda x: (x == "male").sum()),
    female=("sex", lambda x: (x == "female").sum()),
    mean_age=("eeg_age", "mean"),
    std_age=("eeg_age", "std"),
    hsj=("site", lambda x: (x == "hsj").sum()),
    mni=("site", lambda x: (x == "mni").sum()),
    adults=("developmental_group", lambda x: (x == "adult").sum()),
    children=("developmental_group", lambda x: (x == "child").sum()),
    adolescents=("developmental_group", lambda x: (x == "adolescent").sum()),
).reset_index()

# Add combined row for all participants
all_participants = {
    "affected_group": "combined",
    "n": summary_table["n"].sum(),
    "male": summary_table["male"].sum(),
    "female": summary_table["female"].sum(),
    "mean_age": demo_df["eeg_age"].mean().round(2),
    "std_age": demo_df["eeg_age"].std().round(2),
    "hsj": summary_table["hsj"].sum(),
    "mni": summary_table["mni"].sum(),
    "children": summary_table["children"].sum(),
    "adolescents": summary_table["adolescents"].sum(),
        "adults": summary_table["adults"].sum(),

}

summary_table = pd.concat(
    [pd.DataFrame([all_participants]), summary_table], ignore_index=True
)

# Create combined and percentage columns
summary_table["sex (M:F)"] = summary_table["male"].astype(str) + ":" + summary_table["female"].astype(str)
summary_table["sex % (M:F)"] = (
    (summary_table["male"] / summary_table["n"] * 100).round(1).astype(str)
    + ":"
    + (summary_table["female"] / summary_table["n"] * 100).round(1).astype(str)
)

summary_table["site (HSJ:MNI)"] = summary_table["hsj"].astype(str) + ":" + summary_table["mni"].astype(str)
summary_table["site % (HSJ:MNI)"] = (
    (summary_table["hsj"] / summary_table["n"] * 100).round(1).astype(str)
    + ":"
    + (summary_table["mni"] / summary_table["n"] * 100).round(1).astype(str)
)

# Drop intermediate columns to keep the table clean
summary_table.drop(columns=["male", "female", "hsj", "mni"], inplace=True)

# Rename columns for better clarity
summary_table.rename(
    columns={
        "affected_group": "Affected Group",
        "n": "Total Participants",
        "mean_age": "Mean Age",
        "std_age": "Age SD",
        "children": "Children",
        "adolescents": "Adolescents",
                "adults": "Adults",

    },
    inplace=True,
)

# Round the summary table values to 1 decimal places
summary_table = summary_table.round(1)

In [480]:
summary_table

,Affected Group,Total Participants,Mean Age,Age SD,Children,Adolescents,Adults,sex (M:F),sex % (M:F),site (HSJ:MNI),site % (HSJ:MNI)
0,combined,264,27.6,16.6,74,41,149,120:143,45.5:54.2,156:108,59.1:40.9
1,affected,82,23.9,15.6,28,18,36,39:42,47.6:51.2,57:25,69.5:30.5
2,asd,55,15.7,10.2,27,15,13,35:20,63.6:36.4,36:19,65.5:34.5
3,non-affected,127,35.1,15.7,19,8,100,46:81,36.2:63.8,63:64,49.6:50.4

In [481]:
# Add table to the document
doc.add_heading('Demographics breakdown by Affected Status', level=1)
doc = df_to_table(doc, summary_table)

In [482]:
demo_df

,subject,eeg_age,site,sex,asd,ndd,q1k_ID,group,age_group,fam_id,developmental_group,affected_group
0,0042P,30.97,mni,female,0.0,ndd,NaN,proband,adult,0042,adult,affected
1,0043F1,58.13,hsj,male,0.0,control,NaN,father,adult,0043,adult,non-affected
3,0050M1,37.10,hsj,female,0.0,control,NaN,mother,adult,0050,adult,non-affected
4,0050P,8.07,hsj,female,0.0,ndd,NaN,proband,child,0050,child,affected
6,0062P,40.61,hsj,female,0.0,control,NaN,proband,adult,0062,adult,non-affected
...,...,...,...,...,...,...,...,...,...,...,...,...
25,031Z,28.27,mni,male,0.0,control,Q1K_031_Z,NaN,adult,0031,adult,non-affected
26,032Z,18.20,mni,female,0.0,control,Q1K_032_Z,NaN,adult,0032,adult,non-affected
27,033Z,9.88,mni,male,0.0,control,Q1K_033_Z,NaN,child,0033,child,non-affected
28,038Z,10.63,mni,male,0.0,control,Q1K_038_Z,NaN,child,0038,child,non-affected
29,052Z,16.53,mni,female,0.0,control,Q1K_052_Z,NaN,child,0052,adolescent,non-affected

### Summary demographics of only ASD children

In [483]:
# Subset only ASD children
asd_only_df = demo_df[(demo_df.asd == 1) & (demo_df.developmental_group == 'child')]

In [484]:
asd_only_df

,subject,eeg_age,site,sex,asd,ndd,q1k_ID,group,age_group,fam_id,developmental_group,affected_group
9,0064S1,12.22,hsj,male,1.0,ndd,NaN,sibling,child,0064,child,asd
12,0068S1,7.75,mni,male,1.0,ndd,NaN,sibling,child,0068,child,asd
28,0105P,4.39,hsj,female,1.0,ndd,NaN,proband,child,0105,child,asd
72,0171P,12.31,mni,male,1.0,ndd,NaN,proband,child,0171,child,asd
92,0200P,8.97,mni,male,1.0,ndd,NaN,proband,child,0200,child,asd
100,0218P,11.76,mni,male,1.0,ndd,NaN,proband,child,0218,child,asd
102,0223P,10.93,mni,female,1.0,ndd,NaN,proband,child,0223,child,asd
117,0231S2,12.24,mni,male,1.0,ndd,NaN,sibling,child,0231,child,asd
119,0239P,11.34,mni,male,1.0,ndd,NaN,proband,child,0239,child,asd
123,0248S1,11.78,mni,male,1.0,ndd,NaN,sibling,child,0248,child,asd
143,0309P,6.40,mni,male,1.0,ndd,NaN,proband,child,0309,child,asd
148,0326S1,9.01,mni,male,1.0,ndd,NaN,sibling,child,0326,child,asd
179,1042P,10.93,hsj,male,1.0,ndd,NaN,proband,child,1042,child,asd
212,1093S1,7.49,hsj,male,1.0,ndd,NaN,sibling,child,1093,child,asd
213,1093S2,4.20,hsj,female,1.0,control,NaN,sibling,child,1093,child,asd
225,1112P,7.46,hsj,male,1.0,ndd,NaN,proband,child,1112,child,asd
227,1114P,9.45,hsj,female,1.0,ndd,NaN,proband,child,1114,child,asd
233,1121P,9.28,hsj,male,1.0,ndd,NaN,proband,child,1121,child,asd
234,1121S1,11.65,hsj,female,1.0,ndd,NaN,sibling,child,1121,child,asd
240,1134S1,12.81,hsj,male,1.0,ndd,NaN,sibling,child,1134,child,asd
244,1143P,10.11,hsj,female,1.0,ndd,NaN,proband,child,1143,child,asd
258,1162S1,3.95,hsj,male,1.0,ndd,NaN,sibling,child,1162,child,asd
264,1169P,8.37,hsj,male,1.0,ndd,NaN,proband,child,1169,child,asd
267,1182P,12.60,hsj,male,1.0,ndd,NaN,proband,child,1182,child,asd
273,1195P,8.76,hsj,male,1.0,ndd,NaN,proband,child,1195,child,asd
274,1195S1,7.80,hsj,male,1.0,ndd,NaN,sibling,child,1195,child,asd
290,1226P,5.98,hsj,male,1.0,ndd,NaN,proband,child,1226,child,asd

In [485]:
# Summarize data by diagnosis groups
summary_table = asd_only_df.groupby("age_group").agg(
    n=("age_group", "count"),
    male=("sex", lambda x: (x == "male").sum()),
    female=("sex", lambda x: (x == "female").sum()),
    mean_age=("eeg_age", "mean"),
    std_age=("eeg_age", "std"),
    hsj=("site", lambda x: (x == "hsj").sum()),
    mni=("site", lambda x: (x == "mni").sum()),

).reset_index()



# Create combined and percentage columns
summary_table["sex (M:F)"] = summary_table["male"].astype(str) + ":" + summary_table["female"].astype(str)
summary_table["sex % (M:F)"] = (
    (summary_table["male"] / summary_table["n"] * 100).round(2).astype(str)
    + ":"
    + (summary_table["female"] / summary_table["n"] * 100).round(2).astype(str)
)

summary_table["site (HSJ:MNI)"] = summary_table["hsj"].astype(str) + ":" + summary_table["mni"].astype(str)
summary_table["site % (HSJ:MNI)"] = (
    (summary_table["hsj"] / summary_table["n"] * 100).round(2).astype(str)
    + ":"
    + (summary_table["mni"] / summary_table["n"] * 100).round(2).astype(str)
)

# Drop intermediate columns to keep the table clean
summary_table.drop(columns=["male", "female", "hsj", "mni"], inplace=True)

# Rename columns for better clarity
summary_table.rename(
    columns={
        "ndd": "NDD Group",
        "n": "Total Participants",
        "mean_age": "Mean Age",
        "std_age": "Age SD"
    },
    inplace=True,
)

print(summary_table)

  age_group  Total Participants  Mean Age    Age SD sex (M:F)  sex % (M:F)  \
0     child                  27  9.257037  2.689767      21:6  77.78:22.22

  site (HSJ:MNI) site % (HSJ:MNI)
0          17:10      62.96:37.04

In [486]:
summary_table=summary_table.round(1)
summary_table

,age_group,Total Participants,Mean Age,Age SD,sex (M:F),sex % (M:F),site (HSJ:MNI),site % (HSJ:MNI)
0,child,27,9.3,2.7,21:6,77.78:22.22,17:10,62.96:37.04

In [487]:
## Add table to the document
doc.add_heading('Demographics breakdown of ASD Children', level=1)

doc = df_to_table(doc, summary_table)

In [488]:
## Merge the go_df and demo_df
go_df = pd.merge(go_df, demo_df, on="subject", how="inner")

In [489]:
## Rename columns for clarity
go_df.rename(columns={
    "Trial_Index_": "trial_index",
    "GO_SAC_RT": "rt",
    "GO_VALID": "valid_trials",
    "detail": "side"
}, inplace=True)

In [490]:
go_df

,subject,trial_index,condition,side,rt,valid_trials,eeg_age,site,sex,asd,ndd,q1k_ID,group,age_group,fam_id,developmental_group,affected_group
0,002Z,1,Baseline,Right,230.31,True,45.88,mni,female,0.0,control,Q1K_002_Z,NaN,adult,0002,adult,non-affected
1,002Z,2,Gap,Right,255.00,True,45.88,mni,female,0.0,control,Q1K_002_Z,NaN,adult,0002,adult,non-affected
2,002Z,3,Overlap,Left,323.78,True,45.88,mni,female,0.0,control,Q1K_002_Z,NaN,adult,0002,adult,non-affected
3,002Z,4,Gap,Right,197.00,True,45.88,mni,female,0.0,control,Q1K_002_Z,NaN,adult,0002,adult,non-affected
4,002Z,5,Baseline,Left,372.62,True,45.88,mni,female,0.0,control,Q1K_002_Z,NaN,adult,0002,adult,non-affected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9497,1256S2,34,Overlap,Right,368.29,True,18.32,hsj,female,1.0,ndd,NaN,sibling,adult,1256,adult,asd
9498,1256S2,35,Gap,Left,247.00,True,18.32,hsj,female,1.0,ndd,NaN,sibling,adult,1256,adult,asd
9499,1256S2,36,Baseline,Right,211.76,True,18.32,hsj,female,1.0,ndd,NaN,sibling,adult,1256,adult,asd
9500,1256S2,37,Overlap,Right,319.85,True,18.32,hsj,female,1.0,ndd,NaN,sibling,adult,1256,adult,asd
9501,1256S2,38,Gap,Right,323.00,True,18.32,hsj,female,1.0,ndd,NaN,sibling,adult,1256,adult,asd

In [491]:
# Save the go_df to a csv file
go_df.to_csv(f"C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/outputs/gap/go_df.csv", index=False)

# Save new file to specfifc ouputs
go_df.to_csv(f"C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/outputs/gap/extraction/go_df_extraction.csv", index=False)

In [492]:
# Save the document
doc.save(f"C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/outputs/word_document/1_gap_demographics_analysis_results.docx")

# Save backup to archive 
doc.save(f"C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/outputs/word_document/archive/1_gap_demographics_results_{date}.docx")

In [493]:
# Convert missing subjects to a DataFrame
subjects_removed_df = pd.DataFrame.from_dict(subjects_removed, orient='index', columns=['status'])
subjects_removed_df.index.name = 'subject'
# Save the subjects_removed_df to a csv file
subjects_removed_df.to_csv(f"C:/Users/gabot/OneDrive - McGill University/Desktop/github_repos/q1k_neurosubs/outputs/missingness/subjects_removed.csv")